---
- name: Ensure configuration directories
  become: true
  loop:
    - "{{ swag_config_dir }}"
    - "{{ swag_config_dir }}/config"
    - "{{ swag_config_dir }}/config/dns-conf"
    - "{{ swag_config_dir }}/config/nginx/proxy-confs"
  tags:
    - swag
  file:
    path: "{{ item }}"
    state: directory
    owner: >-
      {%- if item == swag_config_dir -%}
      {{ swag_owner }}
      {%- else -%}
      {{ omit }}
      {%- endif -%}
    group: >-
      {%- if item == swag_config_dir -%}
      {{ swag_group }}
      {%- else -%}
      {{ omit }}
      {%- endif -%}
    mode: >-
      {%- if item == swag_config_dir -%}
      {{ swag_dir_mode }}
      {%- else -%}
      {{ omit }}
      {%- endif -%}

- name: Template docker compose file
  become: true
  notify: Reload swag service
  tags:
    - swag
  template:
    src: docker-compose.yml.j2
    dest: "{{ swag_config_dir }}/docker-compose.yml"
    owner: "{{ swag_owner }}"
    group: "{{ swag_group }}"
    mode: "{{ swag_dir_mode }}"

- name: Template .env file
  become: true
  notify: Reload swag service
  tags:
    - swag
  template:
    src: .env.j2
    dest: "{{ swag_config_dir }}/.env"
    owner: "{{ swag_owner }}"
    group: "{{ swag_group }}"
    mode: "{{ swag_file_mode }}"

- name: Ensure swag cert config file
  become: true
  notify: Reload swag service
  when: swag_cert_dns_config is defined
  tags:
    - swag
  copy:
    dest: "{{ swag_config_dir }}/config/dns-conf/{{ swag_cert_dnsplugin }}.{{ swag_cert_config_extension }}"
    content: "{{ swag_cert_dns_config }}"
    mode: "{{ swag_file_mode }}"

- when: ansible_distribution|lower == 'ubuntu'
  include_tasks: ubuntu.yml
  tags:
    - swag

- when: ansible_distribution|lower == 'amazon'
  include_tasks: amazon.yml
  tags:
    - swag

- name: Flush handlers
  meta: flush_handlers
