---
- name: Ensure configuration directories
  become: yes
  loop:
    - "{{ swag_config_dir }}"
    - "{{ swag_config_dir }}/config"
    - "{{ swag_config_dir }}/config/dns-conf"
  tags:
    - swag
  file:
    path: "{{ item }}"
    state: directory
    owner: >-
      {%- if item == swag_config_dir -%}
      {{ swag_owner }}
      {%- else -%}
      {{ omit }}
      {%- endif -%}
    group: >-
      {%- if item == swag_config_dir -%}
      {{ swag_group }}
      {%- else -%}
      {{ omit }}
      {%- endif -%}
    mode: >-
      {%- if item == swag_config_dir -%}
      {{ swag_dir_mode }}
      {%- else -%}
      {{ omit }}
      {%- endif -%}

- name: Template docker compose file
  become: yes
  notify: Reload swag service
  tags:
    - swag
  template:
    src: docker-compose.yml.j2
    dest: "{{ swag_config_dir }}/docker-compose.yml"
    owner: "{{ swag_owner }}"
    group: "{{ swag_group }}"
    mode: "{{ swag_dir_mode }}"

- name: Template .env file
  become: yes
  notify: Reload swag service
  tags:
    - swag
  template:
    src: .env.j2
    dest: "{{ swag_config_dir }}/.env"
    owner: "{{ swag_owner }}"
    group: "{{ swag_group }}"
    mode: "{{ swag_file_mode }}"

- name: Ensure swag cert config file
  become: yes
  notify: Reload swag service
  when: swag_cert_dns_config is defined
  tags:
    - swag
  copy:
    dest: "{{ swag_config_dir }}/config/dns-conf/{{ swag_cert_dnsplugin }}.{{ swag_cert_config_extension }}"
    content: "{{ swag_cert_dns_config }}"
    mode: "{{ swag_file_mode }}"

- name: Template swag service file
  become: yes
  notify: Reload swag service
  tags:
    - swag
  template:
    src: swag.service.j2
    dest: /etc/systemd/system/swag.{{ swag_server_domain }}.service
    owner: root
    group: root
    mode: "755"

- meta: flush_handlers
